
version: '3.2'

networks:
  dev_network:

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: admin
      POSTGRES_DB: flask_netology
      POSTGRES_HOST_AUTH_METHOD: trust

    ports:
    - 5432:5432

    networks:
      dev_network:
        aliases:
          - db

  app:
    build:
      context: .
      args:
        PG_DSN: 'postgresql://admin:1234@db:5432/flask_netology'
    ports:
      - "5000:5000"
    container_name: app
    depends_on:
      - db
    networks:
      dev_network:
        aliases:
          - flask_api
    volumes:
      - ./:/app


