

version: '3.9'

networks:
  dev_network:

services:
  app:
    build:
      context: .
      args:
        PG_DSN: 'postgresql://admin:1234@db-main:5432/flask_netology'
    ports:
      - "5000:5000"
    container_name: app
    depends_on:
      db:
        condition: service_healthy
    networks:
      dev_network:
        aliases:
          - flask_api
    restart:
      always
    volumes:
      - ./:/app


  db:
    build: db
    ports:
      - "5432:5432"
    container_name: users_api_db_main
    networks:
      dev_network:
        aliases:
          - db-main
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
